apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
spec:
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-serviceaccount-key
      containers:
      - name: metrics-generator
        image: eu.gcr.io/bu-fyp-s5008913/metrics-generator@sha256:1d1eb849413a9c6cf4720b5a86dc9aa2af5064e49031b62eff45335ebdf9f204
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: RUN_DELAY_SECONDS
          valueFrom:
            configMapKeyRef:
              key: RUN_DELAY_SECONDS
              name: metrics-generator-config
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: API_ENDPOINT
              name: metrics-generator-config
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              key: API_KEY
              name: metrics-generator-config
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json