apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
spec:
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-serviceaccount-key
      containers:
      - name: metrics-generator
        image: eu.gcr.io/bu-fyp-s5008913/metrics-generator@sha256:4b4942bfc64e42a698f38b97abca8d7bed5bc1fe23ad86e21bfa2d673f390f80
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: RUN_DELAY_SECONDS
          valueFrom:
            configMapKeyRef:
              key: RUN_DELAY_SECONDS
              name: metrics-generator-config
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: API_ENDPOINT
              name: metrics-generator-config
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              key: API_KEY
              name: metrics-generator-config
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json